### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by OakP** [seppukudevelopment/seppuku#26]
Hey, listen, I have some questions for you. Look, you have events in your client, why do they work? There after all only the name of the class and Extend EventCancellable. And in General, if I add any event to my client, not just for you, and if I add the minecraft function, it just crashes. Can you explain these points ? I also write on version 1.12.2 forge.

**Comment by cookiedragon234** [comment]
Hey, listen, I have some questions for you too. Look, if you make a custom event bus, you can make it accept classes that extend object rather than some event class. And in general, if you go copy pasting other people’s code, it won’t work! Luckily we have @ethug here to make epic event buses for us! I also write on 1.12.2 forge.

**Comment by ethug** [comment]
Please keep issues related to Seppuku.
